### PR TITLE
added error string from image-size

### PR DESCRIPTION
**Pull request by spicfrankly**
The "Unknown image format" is more helpful with the error message from image-size

### CODE REVIEW

**Comment by bartbutenaers** [comment]
Hi @spicfrankly,
Thanks for your contribution!
That indeed makes sense.
It has been published as version **0.1.1** on NPM.
Bart

**Comment by spicfrankly** [comment]
Hi Bart,
No worries, thanks for the published update!
I also noticed tiff images aren't supported as buffers in image-size, only as file path string. Thus are you often using string buffers as input to the node ? Would you consider using strings only as file paths instead?
Cheers
Sam

Dec 12, 2019 10:37:16 AM bartbutenaers <notifications@github.com>:

Hi @spicfrankly<https://github.com/spicfrankly>,
Thanks for your contribution!
That indeed makes sense.
It has been published as version 0.1.1 on NPM.
Bart

**Comment by bartbutenaers** [comment]
Hey Sam,
How did you notice that tiff images aren't supported as buffers in image-size, only as file path string?  I don't see anything about that in their documentation.  
Bart

**Comment by spicfrankly** [comment]
Hi Bart,
When I sent a tiff file content to the node, I received this error from the image-size exception message: https://github.com/image-size/image-size/blob/c52364846a4154f817b63637961e881e2b726078/lib/types/tiff.ts#L93

**Comment by bartbutenaers** [comment]
Sam,
thanks for the information!
Then indeed we would have to allow file paths as input.
Had a quick look at my [code ](https://github.com/bartbutenaers/node-red-contrib-image-info/blob/master/image_info.js#L40) but when a file path would be injected, we would arrive at line 40:

image

Seems that - for some reason - I have allowed (at the time being) normal strings which are converted to a buffer.  And **_I don't want to have any impact on existing flows_**!  Suppose somebody is already using this node with a (non base64) string as input, then his flow would be broken if we would put file-based stuff on line 40...  On the other hand I'm now doubting whether such flows would exist: indeed I think that an image as a (non base64) string would be corrupt anyway.  So I think we can put our file stuff on line 40...   Do you have any thoughts about this?

If you should have some free time left, it would be nice if you could create a new pull request to get it done. 

Kind regards,
Bart

**Comment by spicfrankly** [comment]
I did the change locally on another machine. I'll send you a pull request on the next week.
Cheers

**Pull request merged**
